### PR TITLE
Fix rubocop warnings

### PR DESCRIPTION
**Pull request by ares**
Jenkins test running at http://ci.theforeman.org/job/test_develop_pull_request/9733/

### CODE REVIEW

**Comment by ares** [comment]
Test triggered here http://ci.theforeman.org/job/test_develop_pr_core/3322/

**Comment by GregSutcliffe** [comment]
+1 pending tests

**Comment by ares** [comment]
New version test running http://ci.theforeman.org/job/test_develop_pr_core/3325/

**Comment by ares** [comment]
It's green \o/

**Comment by GregSutcliffe** [comment]
Squash-merged, thanks

**Pull request closed without merging**
